services:
  - type: web
    name: lifeflow
    env: docker
    dockerfilePath: ./lifeflow/Dockerfile
    dockerContext: ./lifeflow
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
